### ISSUE TITLE
Suspected incorrect coverage counts and confusing html output

### ISSUE THREAD

**Issue by nothingrandom** [istanbuljs/nyc#1421]
## Link to bug demonstration repository

I understand why this is a requirement, but this is a 5 year old codebase with business logic behind it. I'd be happy to extract a part of it and provide access to just those able to provide further assisstance.

`package.json`
```json
"scripts": {
    "gulp": "gulp",
    "test": "cross-env TS_NODE_COMPILER_OPTIONS={\\\"module\\\":\\\"commonjs\\\"} node_modules/.bin/mocha --require @babel/register --require ts-node/register -r ./test/setup.js \"app/scripts.babel/**/*.spec.@(js|jsx)\"",
    "test:coverage": "nyc npm run test"
  }
```

`nycrc.yaml`
```yaml
all: true
check-coverage: true
require: ['@babel/register']
extension:
  - .js
  - .jsx
include:
  - app/scripts.babel/**/*.js
  - app/scripts.babel/**/*.jsx
exclude:
  - app/scripts.babel/*.js
  - app/scripts.babel/*.jsx
  - app/scripts.babel/background/index.js
  - app/scripts.babel/browser/index.js
  - app/scripts.babel/browser/chrome/openOptionsPage.js
  - app/scripts.babel/frontend/content-popup/index.js
  - app/scripts.babel/frontend/options/index.js
  - app/scripts.babel/frontend/popup/index.js
  - app/scripts.babel/modules/reducers.js
  - app/scripts.babel/redux/createStore.js
  - app/scripts.babel/redux/index.js
  - app/scripts.babel/redux/reducers.js
  - app/scripts.babel/modules/session/actionCreators/internal/getResourceDomainId.js
  - app/scripts.babel/contentScript/handleCaching.js
  - app/scripts.babel/contentScript/handleOpenClose.js
  - app/scripts.babel/contentScript/index.js
  - app/scripts.babel/contentScript/initialize.js
  - app/scripts.babel/contentScript/runConentScript.js
  - app/scripts.babel/contentScript/workflow/images.js
  - app/scripts.babel/contentScript/workflow/runConentScript.js

reporter:
  - lcov
  - cobertura
statements: 79.74
branches: 46.84
functions: 83.73
lines: 97.07
```

## Expected Behavior
Clear html coverage output and correct counts for statements, branches, and functions.

## Observed Behavior
79.66% Statements `18322/23001`
46.7% Branches `5355/11466`
83.6% Functions `4915/5879`
97.07% Lines `16590/17091`

From the line count, I would expect S/B/F to have a higher % count. It has been previously seen as having a higher count, but after making an addition to the test script `TS_NODE_COMPILER_OPTIONS={\\\"module\\\":\\\"commonjs\\\"}`, whilst adding support for Typescript S/B/F dropped whilst Lines remained the same.

Further, and this is from *before* the test script change, the output code coverage html has a mix of randomly red highlighted sections (middle of words, middle of lines). There are also `const` statements, and commented lines with the message `if/else path not taken`.

<img width="691" alt="Screen Shot 2021-07-22 at 14 07 42" src="https://user-images.githubusercontent.com/5164938/126636728-20946e63-7307-4fa4-9c5a-9d38f8854144.png">

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

```zsh
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 77.59 MB / 16.00 GB
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/Documents/Git/lean-library-extension/node_modules/.bin/npm
  npmPackages:
    @babel/core: ^7.9.6 => 7.14.5 
    @babel/preset-env: ^7.9.6 => 7.14.5 
    @babel/preset-react: ^7.9.4 => 7.14.5 
    @babel/register: ^7.9.0 => 7.14.5 
    @rollup/plugin-babel: ^5.0.0 => 5.3.0 
    babel-plugin-lodash: ^3.3.4 => 3.3.4 
    babelify: ^10.0.0 => 10.0.0 
    gulp-babel: ^8.0.0 => 8.0.0 
    nyc: ^15.0.0 => 15.0.0 
    ts-node: ^10.0.0 => 10.0.0 
    typescript: ^4.3.4 => 4.3.4 

```
