### ISSUE TITLE
CircleCI Coverage Artifacts

### ISSUE THREAD

**Issue by joncursi** [istanbuljs/nyc#372]
How might one edit their `circle.yml` file to enable the upload and viewing of HTML coverage results after the test suite runs? Is this currently possible?

**Comment by JaKXz** [comment]
@joncursi this is possible with the `lcov` or `html` reporters:

```yml
general:
  artifacts:
    - "./coverage/lcov-report/"
```
