### ISSUE TITLE
Yargs related error on nyc using it with mocha

### ISSUE THREAD

**Issue by anonrig** [istanbuljs/nyc#712]
Hello,

I'm receiving this error on CircleCI with NodeJs 8.8.0, but on local machine working it with 8.6.0 I don't receive this error. I don't think that it's related to node version but let me point it out :)

```bash
> faida-core@0.1.0 test /home/circleci/repo
> CONFIG=config/test.json ./node_modules/.bin/nyc --reporter=html --reporter=text --all ./node_modules/.bin/mocha --require ./test/index.js "test/**/*.js"

YError: Invalid first argument. Expected string or function but received boolean.
    at argumentTypeError (/home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:70:9)
    at /home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (<anonymous>)
    at module.exports (/home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.version (/home/circleci/repo/node_modules/nyc/node_modules/yargs/yargs.js:715:5)
    at Object.Config.buildYargs (/home/circleci/repo/node_modules/nyc/lib/config-util.js:213:6)
    at Object.<anonymous> (/home/circleci/repo/node_modules/nyc/bin/nyc.js:20:54)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
YError: Invalid first argument. Expected string or function but received boolean.
    at argumentTypeError (/home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:70:9)
    at /home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (<anonymous>)
    at module.exports (/home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.version (/home/circleci/repo/node_modules/nyc/node_modules/yargs/yargs.js:715:5)
    at Object.Config.buildYargs (/home/circleci/repo/node_modules/nyc/lib/config-util.js:213:6)
    at Object.<anonymous> (/home/circleci/repo/node_modules/nyc/bin/nyc.js:66:16)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
info: Reading config file config/test.json
```

**Comment by AdamVig** [comment]
I got the same error on my local machine (macOS High Sierra 10.13.1) with `npm run test`. My test script is `PORT=7863 nyc ava`.

**Comment by bcoe** [comment]
@anonrig @AdamVig could you share a link to a project (or a minimal reproduction) that is having this issue? From reading that stack trace, it looks like the issue is related to the parsing of a field in `test.json`.

**Comment by anonrig** [comment]
I can not reproduce this error on my local machine, but if it's helpful here is the `.circleci/config.yml`

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint
      - run: npm test

      - store_artifacts:
          path: coverage

```
